add support for multiple tokens
jedfonner/MattermostOnFire pull request #3
Opened 2018-01-10 09:36 UTC by McFoggy

In case the mattermost installation contains multiple teams, and that several slash commands are deployed separately in each team, then the need for multiple slash command id (tokens) is required.

This PR provide the minimum to handle this case.

_PS: not being a JS dev there are probaly more elegant ways of achieving this._

2018-01-15 02:11 UTC, jedfonner requested changes
Great addition!  I left just a few comments.  Once you address them, I'll merge it in.

2018-01-15 02:11 UTC, jedfonner commented on README.md
> +### Deploying slash command to multiple mattermost teams
The way you've added this to the end means it appears to be a sub-section of "Developing".  

Instead, please move it up under "Finish Firebase Setup" and just add the text and skip the "Deploying slash command to multiple mattermost teams" section header.

2018-01-15 02:11 UTC, jedfonner commented on functions/utils.js
> +  var tokens = MM_INTEGRATION_TOKEN?MM_INTEGRATION_TOKEN.split(','):[];
Small nit: please add spaces around the operators.

2018-01-15 02:11 UTC, jedfonner commented on README.md
> +On a single installation, if you have multiple mattermost teams and want to use the slash command on each, then you have to register several tokens (one for each slash command created).
Please uppercase the first M in "mattermost" (should be "Mattermost teams...")

2018-01-15 06:36 UTC, McFoggy commented
If you want me to squash in order to remove the 'cosmetic' second commit, please ask.  
I left it to ease your review.

2018-01-16 12:23 UTC, jedfonner approved these changes

2018-01-16 12:23 UTC, jedfonner commented
Go ahead and squash and I'll merge.  Thanks again for this!

2018-01-16 12:48 UTC, McFoggy commented
@jedfonner done!

2018-01-16 14:26 UTC, merged